import { IDataTableColumn } from "react-data-table-component";

export const HeadersColumns: IDataTableColumn[] =
    [
        { name: "Fecha Movimiento", selector: "", center: true },
        { name: "Fecha Afectacion", selector: "", center: true },
        { name: "Tipo Mov", selector: "", center: true },
        { name: "Nombre Cuenta", selector: "", center: true },
        { name: "Empresa", selector: "", center: true },
        { name: "Producto", selector: "", center: true },
        { name: "Tipo Linea Dist.", selector: "", center: true },
        { name: "ReferenciaID", selector: "", center: true },
        { name: "Referencia", selector: "", center: true },
        { name: "Sucursal Cartera", selector: "", center: true },
        { name: "No Cda", selector: "", center: true },
        { name: "Cve Cli", selector: "", center: true },
        { name: "Mov Cli", selector: "", center: true },
        { name: "Plazo", selector: "", center: true },
        { name: "Nombre Cliente", selector: "", center: true },
        { name: "ReferenciaID", selector: "", center: true },
        { name: "Capital", selector: "", center: true },
        { name: "Intereses", selector: "", center: true },
        { name: "Manejo de Cuenta", selector: "", center: true },
        { name: "Seguro", selector: "", center: true },
        { name: "Iva Porc", selector: "", center: true },
        { name: "Otros", selector: "", center: true },
        { name: "Apertura Porc", selector: "", center: true },
        { name: "Importe", selector: "", center: true },
        { name: "VentasTotalesTiendita", selector: "", center: true },
        { name: "Fecha Desembolso", selector: "", center: true },
        { name: "Cuenta Desembolso", selector: "", center: true },
        { name: "Fol Apl", selector: "", center: true },
        { name: "Balance", selector: "", center: true },
        { name: "Nombre Balance", selector: "", center: true },
        { name: "Sucursal Gasto", selector: "", center: true },
        { name: "Empresa Gasto", selector: "", center: true },
        { name: "Encargado", selector: "", center: true },
        { name: "Empresa Fiscal", selector: "", center: true },
        { name: "Dias Atrazo", selector: "", center: true },
        { name: "Num Usuario Aplica", selector: "", center: true },
        { name: "Nombre Aplica Mov", selector: "", center: true },
        { name: "idGpo", selector: "", center: true },
        { name: "ConfiaShop", selector: "", center: true },
        { name: "DistribuidorID", selector: "", center: true },
        { name: "Tipo Credito", selector: "", center: true },
    ];