export interface IPermiso {
    ProductoID: number,
    ProductoNombre: string,
    ProductoActivo: boolean,
    ProductoPrincipal: boolean,
    EmpresaId: number,
    EmpresaNombre: string,
    ModuloID: number,
    ModuloNombre: string,
    ModuloRuta: string,
    ModuloColorBorde: string,
    ModuloColorFondo: string,
    ModuloColorFuente: string,
    ModuloIcono: string,
    PantallaID: number,
    PantallaNombre: string,
    PantallaDescripcion: string,
    PermisoID: number,
    PermisoNombre: string,
    PermisoDescripcion: string,
    PermisoEspecial: boolean,
    PermisoRestUrl: string,
    PermisoRestMetodo: string,
    UsuarioID: number
}