export const CATALOGOS__IDENTIFICACIONES_QUERY: string = "CATALOGOS__IDENTIFICACIONES_QUERY"
export const CATALOGOS__IDENTIFICACIONES_OK: string = "CATALOGOS__IDENTIFICACIONES_OK"
export const CATALOGOS__IDENTIFICACIONES_ERROR: string = "CATALOGOS__IDENTIFICACIONES_ERROR"

export const CATALOGOS__SEXOS_QUERY: string = "CATALOGOS__SEXOS_QUERY"
export const CATALOGOS__SEXOS_OK: string = "CATALOGOS__SEXOS_OK"
export const CATALOGOS__SEXOS_ERROR: string = "CATALOGOS__SEXOS_ERROR"

export const CATALOGOS__ESTADO_CIVIL_QUERY: string = "CATALOGOS__ESTADO_CIVIL_QUERY"
export const CATALOGOS__ESTADO_CIVIL_OK: string = "CATALOGOS__ESTADO_CIVIL_OK"
export const CATALOGOS__ESTADO_CIVIL_ERROR: string = "CATALOGOS__ESTADO_CIVIL_ERROR"

export const CATALOGOS__ESCOLARIDADES_QUERY: string = "CATALOGOS__ESCOLARIDADES_QUERY"
export const CATALOGOS__ESCOLARIDADES_OK: string = "CATALOGOS__ESCOLARIDADES_OK"
export const CATALOGOS__ESCOLARIDADES_ERROR: string = "CATALOGOS__ESCOLARIDADES_ERROR"

export const CATALOGOS__OCUPACIONES_QUERY: string = "CATALOGOS__OCUPACIONES_QUERY"
export const CATALOGOS__OCUPACIONES_OK: string = "CATALOGOS__OCUPACIONES_OK"
export const CATALOGOS__OCUPACIONES_ERROR: string = "CATALOGOS__OCUPACIONES_ERROR"

export const CATALOGOS__VIALIDADES_TIPO_QUERY: string = "CATALOGOS__VIALIDADES_TIPO_QUERY"
export const CATALOGOS__VIALIDADES_TIPO_OK: string = "CATALOGOS__VIALIDADES_TIPO_OK"
export const CATALOGOS__VIALIDADES_TIPO_ERROR: string = "CATALOGOS__VIALIDADES_TIPO_ERROR"

export const CATALOGOS__ORIENTACION_VIALIDADES_TIPO_QUERY: string = "CATALOGOS__ORIENTACION_VIALIDADES_TIPO_QUERY"
export const CATALOGOS__ORIENTACION_VIALIDADES_TIPO_OK: string = "CATALOGOS__ORIENTACION_VIALIDADES_TIPO_OK"
export const CATALOGOS__ORIENTACION_VIALIDADES_TIPO_ERROR: string = "CATALOGOS__ORIENTACION_VIALIDADES_TIPO_ERROR"

export const CATALOGOS__VIVIENDAS_TIPO_QUERY: string = "CATALOGOS__VIVIENDAS_TIPO_QUERY"
export const CATALOGOS__VIVIENDAS_TIPO_OK: string = "CATALOGOS__VIVIENDAS_TIPO_OK"
export const CATALOGOS__VIVIENDAS_TIPO_ERROR: string = "CATALOGOS__VIVIENDAS_TIPO_ERROR"

export const CATALOGOS__ESTATUS_CREDITO_QUERY: string = "CATALOGOS__ESTATUS_CREDITO_QUERY"
export const CATALOGOS__ESTATUS_CREDITO_OK: string = "CATALOGOS__ESTATUS_CREDITO_OK"
export const CATALOGOS__ESTATUS_CREDITO_ERROR: string = "CATALOGOS__ESTATUS_CREDITO_ERROR"

export const CATALOGOS__ESTADO_DISTRIBUIDOR_QUERY: string = "CATALOGOS__ESTADO_DISTRIBUIDOR_QUERY"
export const CATALOGOS__ESTADO_DISTRIBUIDOR_OK: string = "CATALOGOS__ESTADO_DISTRIBUIDOR_OK"
export const CATALOGOS__ESTADO_DISTRIBUIDOR_ERROR: string = "CATALOGOS__ESTADO_DISTRIBUIDOR_ERROR"

export const CATALOGOS__PAGARE_ESTATUS_QUERY: string = "CATALOGOS__PAGARE_ESTATUS_QUERY"
export const CATALOGOS__PAGARE_ESTATUS_OK: string = "CATALOGOS__PAGARE_ESTATUS_OK"
export const CATALOGOS__PAGARE_ESTATUS_ERROR: string = "CATALOGOS__PAGARE_ESTATUS_ERROR"

export const CATALOGOS__ASENTAMIENTO_QUERY: string = "CATALOGOS__ASENTAMIENTO_QUERY"
export const CATALOGOS__ASENTAMIENTO_OK: string = "CATALOGOS__ASENTAMIENTO_OK"
export const CATALOGOS__ASENTAMIENTO_ERROR: string = "CATALOGOS__ASENTAMIENTO_ERROR"

export const CATALOGOS__ESTADO_PAIS_QUERY: string = "CATALOGOS__ESTADO_PAIS_QUERY"
export const CATALOGOS__ESTADO_PAIS_OK: string = "CATALOGOS__ESTADO_PAIS_OK"
export const CATALOGOS__ESTADO_PAIS_ERROR: string = "CATALOGOS__ESTADO_PAIS_ERROR"

export const CATALOGOS__TIPO_VIVIENDA_QUERY: string = "CATALOGOS__TIPO_VIVIENDA_QUERY"
export const CATALOGOS__TIPO_VIVIENDA_OK: string = "CATALOGOS__TIPO_VIVIENDA_OK"
export const CATALOGOS__TIPO_VIVIENDA_ERROR: string = "CATALOGOS__TIPO_VIVIENDA_ERROR"

export const CATALOGOS__EMPRESAS_EXPERIENCIA_QUERY: string = "CATALOGOS__EMPRESAS_EXPERIENCIA_QUERY"
export const CATALOGOS__EMPRESAS_EXPERIENCIA_OK: string = "CATALOGOS__EMPRESAS_EXPERIENCIA_OK"
export const CATALOGOS__EMPRESAS_EXPERIENCIA_ERROR: string = "CATALOGOS__EMPRESAS_EXPERIENCIA_ERROR"

export const CATALOGOS__PARENTESCO_QUERY: string = "CATALOGOS__PARENTESCO_QUERY"
export const CATALOGOS__PARENTESCO_OK: string = "CATALOGOS__PARENTESCO_OK"
export const CATALOGOS__PARENTESCO_ERROR: string = "CATALOGOS__PARENTESCO_ERROR"

export const CATALOGOS__STATUSPROCESO_QUERY: string = "CATALOGOS__STATUSPROCESO_QUERY"
export const CATALOGOS__STATUSPROCESO_OK: string = "CATALOGOS__STATUSPROCESO_OK"
export const CATALOGOS__STATUSPROCESO_ERROR: string = "CATALOGOS__STATUSPROCESO_ERROR"

export const CATALOGOS__TIPO_DISTRIBUIDOR_QUERY: string = "CATALOGOS__TIPO_DISTRIBUIDOR_QUERY"
export const CATALOGOS__TIPO_DISTRIBUIDOR_OK: string = "CATALOGOS__TIPO_DISTRIBUIDOR_OK"
export const CATALOGOS__TIPO_DISTRIBUIDOR_ERROR: string = "CATALOGOS__TIPO_DISTRIBUIDOR_ERROR"

export const CATALOGOS__EMPRESAS_QUERY: string = "CATALOGOS__EMPRESAS_QUERY"
export const CATALOGOS__EMPRESAS_OK: string = "CATALOGOS__EMPRESAS_OK"
export const CATALOGOS__EMPRESAS_ERROR: string = "CATALOGOS__EMPRESAS_ERROR"